name: Hello World
author: Nelson Perez
description: some description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Fulano
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node12"
  main: "dist/index.js"
