on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: SayHello
        uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World"
          
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo ${HELLO}
      