name: "Open Github Issue"
author: nelsonrp24
description: "Opens a github issue"

inputs:
  token:
    description: "Github Token"
    required: true
  tittle:
    description: "Issue Title"
    required: true
  body:
    description: "Issue Body"
  assignees:
    description: "Issue Assignees"
outputs:
  issue:
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "dist/index.js"
